image: maven:latest

variables:
  MAVEN_OPTS:
    -Dmaven.repo.local=/cache/lusc8520/certainlyuncertain-se2-hausarbeit/.m2/repository

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script: mvn compile

unit-test-job:
  stage: test
  script:
    - "mvn test"

deploy-job:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get install rsync -y
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mvn package -DskipTests
    - "rsync -az -progress -e 'ssh -o StrictHostKeyChecking=no' target/cuse2ha.jar fb3pooluser@192.168.45.33:"
    - ssh -o StrictHostKeyChecking=no fb3pooluser@192.168.45.33 tmux kill-session -t mySession 2>/dev/null || true
    - ssh -o StrictHostKeyChecking=no fb3pooluser@192.168.45.33 "tmux new -d -s mySession 'java -jar cuse2ha.jar'"
  only:
    - main